Mixpanel/AutomaticProperties.swift, Mixpanel/Error.swift, Mixpanel/FileLogging.swift, Mixpanel/JSONHandler.swift, Mixpanel/MixpanelInstance.swift, Mixpanel/Network.swift, Mixpanel/Persistence.swift
Please take a look if possible. Thanks.
=> support for xcode 8 beta 4

README.md
I found by testing that Autotrack does not work with this framework, you must use the Objective-C one.
=> Adding autotrack support information

Mixpanel/People.swift
Same fix as in mixpanel/mixpanel-iphone#571
=> removePushDeviceToken fix

Mixpanel.xcodeproj/xcshareddata/xcschemes/Mixpanel_tvOS.xcscheme
=> Add Mixpanel_tvOS.xcscheme

Mixpanel/MixpanelInstance.swift
fixes https://github.com/mixpanel/mixpanel-swift/issues/89
=> stop calling UIApplication methods from background thread

Mixpanel/MixpanelInstance.swift
This PR fixes compilation without DECIDE flag
=> Fix compilation without DECIDE flag

Mixpanel/MixpanelInstance.swift, Mixpanel/TweakPersistency.swift, Mixpanel/Variant.swift, Mixpanel/VariantTweak.swift
change db location of tweaks, and execute tweaks from cached mixpanel archives after Tweaks have been initialized
=> change db location of tweaks

Mixpanel/MixpanelInstance.swift
create an addtional param to allow the disabling of user profile updates after identifying
=> identify method option to disable people updates

Mixpanel/AutomaticEvents.swift, Mixpanel/MixpanelInstance.swift, MixpanelDemo/MixpanelDemo/AppDelegate.swift
update to automatically track UNUserNotifications framework and fix for Appex with calling UIApplication.shared
=> update to automatically track UNUserNotifications framework and fix

Mixpanel/Constants.swift
https://developer.apple.com/ios/human-interface-guidelines/overview/iphone-x/
=> move up mini inapp to be in safe area as in guidelines

Mixpanel/People.swift, docs/docsets/Mixpanel.docset/Contents/Resources/Documents/Classes/People.html
Update union method documentation per customer feedback.
=> Update union method documentation

Mixpanel/TakeoverNotificationViewController~iphoneportrait.xib
There is a fix to the constraint of the button
=> Two-buttun, full screen in-apps don't fit on iPhoneX

Mixpanel/Flush.swift, Mixpanel/Mixpanel.swift, Mixpanel/MixpanelInstance.swift, Mixpanel/Network.swift, Mixpanel/People.swift, Mixpanel/Persistence.swift, Mixpanel/SessionMetadata.swift, Mixpanel/Track.swift, MixpanelDemo/MixpanelDemo.xcodeproj/project.pbxproj, MixpanelDemo/MixpanelDemo.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, MixpanelDemo/MixpanelDemoTests/MixpanelBaseTests.swift, MixpanelDemo/MixpanelDemoTests/MixpanelDemoTests.swift, MixpanelDemo/MixpanelDemoTests/MixpanelOptOutTests.swift
Background of this change:
In April, 2016, the European Union’s governing bodies passed the General Data Protection Regulation (GDPR), a set of standards and requirements for protecting the privacy and personal information of EU residents. These requirements serve to establish a uniform standard across all EU member states, but do raise the bar above current general practice. They go into effect, in May, 2018.
=> Gdpr support

.travis.yml, Mixpanel/ConnectIntegrations.swift, Mixpanel/MD5.swift, Mixpanel/MixpanelInstance.swift, Mixpanel/ObjectFilter.swift
Fix build warning in library for XCode 9.3 and swift 4.1
=> Swift compile issue

Mixpanel.xcodeproj/project.pbxproj, Mixpanel/ExceptionWrapper.h, Mixpanel/ExceptionWrapper.m, Mixpanel/Mixpanel.h, Mixpanel/Persistence.swift, MixpanelDemo/MixpanelDemoTests/MixpanelDemoTests.swift
Add try catch to unarchive to prevent any crash from unarchive corrupted data
=> Add try catch to unarchive 

Mixpanel/People.swift
Hi!
I just want to bring missing function from `mixpanel-iphone` to swift version
=> Allow to remove All device push tokens

Mixpanel/AutomaticEvents.swift, Mixpanel/Flush.swift, Mixpanel/MixpanelInstance.swift, Mixpanel/People.swift, Mixpanel/Persistence.swift, Mixpanel/SessionMetadata.swift
Tweaks:
-All async dispatches are weak self, with proper safety checks for self DNE on execution. 
-Fixed captures for ExceptionWrapper
-All async dispatches should now have explicit immutable captures of their inputs, which help should prevent bad_access errors. 
-I switched one DispatchQueue.main.sync -> .async, as it looked like a typo. I noticed there were a few other main.sync calls in the project but I didn't know enough about why you might need them to change them. I would recommend avoiding that unless absolutely necessary. If it must be done, a check like:
```
if Thread.isMainThread {
/// do work
} else {
DispatchQueue.main.sync {
/// do work
}
}
```
Adds 100% safety.
Some other things I noticed poking around:
-Generally speaking, it's best to avoid ever writing out "self." since …
=> Async dispatch audit

Mixpanel/MixpanelInstance.swift, Mixpanel/People.swift, Mixpanel/Track.swift
inout parameter is not thread safe and can lead to crash due to EXC_BAD_ACCESS
=> fix a potential crash issue by fetching the current super properties

Mixpanel/Flush.swift
https://github.com/mixpanel/mixpanel-swift/issues/298
=> fix deadlock in readwrite lock

Mixpanel/AutomaticEvents.swift
=> Added check for automaticPushTracking

Mixpanel/Decide.swift, Mixpanel/JSONHandler.swift
https://github.com/mixpanel/mixpanel-swift/issues/302
=> fix A/B Developer tweaks won't update

.travis.yml, Mixpanel/Logger.swift, Mixpanel/MD5.swift, Mixpanel/MixpanelInstance.swift, Mixpanel/Persistence.swift, MixpanelDemo/MixpanelDemoTests/MixpanelABTestingTests.swift, MixpanelDemo/MixpanelDemoTests/MixpanelBaseTests.swift, MixpanelDemo/MixpanelDemoTests/MixpanelDemoTests.swift, MixpanelDemo/MixpanelDemoTests/MixpanelOptOutTests.swift, MixpanelDemo/MixpanelDemoTests/MixpanelPeopleTests.swift
Fix issues: 
1. Fix a rare case where a race case could happen for Logger
2. Fix the race condition/crash for `archive`
Related issue:
https://github.com/mixpanel/mixpanel-swift/issues/327
=> Xcode 11 support and race condition fixes

.travis.yml, Mixpanel/Flush.swift
This fix the issue where offline mode can't archive properly
=> fix offline not being able to archive properly

Mixpanel-swift.xcconfig, Mixpanel.xcodeproj/project.pbxproj, Mixpanel/MiniNotificationViewController.swift, Mixpanel/TakeoverNotificationViewController.swift
- Fix mini notification not showing properly in some devices.
- Fix In-apps not showing up for iOS 13 with Scenes.
=> fix in app notification not showing or showing correctly in iOS 13

Mixpanel/Flush.swift, Mixpanel/Network.swift
Add logging to the URLs fetched by the library
Add logging to the batch of events/profile updates being sent to the API
=> Enhanced Logging

Mixpanel/Flush.swift
Fix the issue where events not being able to be flushed beyond the batch size.
=> fix a typo in the flush logic

Mixpanel/Persistence.swift, MixpanelDemo/MixpanelDemoTests/MixpanelOptOutTests.swift
include:
https://github.com/mixpanel/mixpanel-swift/pull/361
all credits to @RamblinWreck77
=> optimize persistence logic

Mixpanel/MixpanelInstance.swift
This will likely fix crash from currentRadioAccessTechnology and support Dual SIM
=> Fix deprecated `currentRadioAccessTechnology` in CTTelephonyNetworkInfo

Mixpanel/Network.swift
fix issue https://github.com/mixpanel/mixpanel-swift/issues/332.
=> fix potential crash from check decide

Mixpanel/DeviceInfoMessage.swift, Mixpanel/MixpanelInstance.swift
=> Fixed two minor build warnings for Xcode 11.4b3

Sources/AutomaticProperties.swift, release.py
Forgot to checkin AutomaticProperties.swift after bumping the version.
=> fix release script

Sources/MixpanelInstance.swift, Sources/TweakPersistency.swift
https://github.com/mixpanel/mixpanel-swift/issues/402
=> update deprecated archiving apis

Sources/MixpanelType.swift
Added NSArray type to MixpanelType. Needed this type while working with deserialized JSON
=> Add NSArray support to MixpanelType

Sources/MixpanelInstance.swift
Fix crash in persistence.archiveToFile caused by race conditions from variant changes and group updates. 
Address the issue: 
https://github.com/mixpanel/mixpanel-swift/issues/431
=> Fix crash in persistence.archiveToFile

Sources/Decide.swift
Address #450 , removing the code cause it has more side effects than its purpose.
=> No longer overwriting isIdleTimerDisabled value

Sources/Mixpanel.swift
Fixes https://github.com/mixpanel/mixpanel-swift/issues/524
I'm not exactly sure why this deadlocks in Mac when using SwiftUI (I'm on an M1). I've verified it only happens when initializing in a SwiftUI app. In any case, the semaphore should not be needed because it's the same behavior that `DispatchQueue.sync` does.
Changes in this PR:
1. Change `instanceQueue.async` to `instanceQueue.sync`.
2. Remove the any semaphore code.
3. Remove the `self` references to match code style now that the closure is non-escaping.
I've tested this works correctly and doesn't cause a deadlock on Mac M1. I have not tested how this affects iOS or other platforms.
If I may give an additional recommendation. I suggest changing the QoS of the `instanceQueue` dispatch queue from `.utility` to `.default`. This is …
=> Fix deadlock in initialization

MixpanelDemo/MixpanelDemo/AppDelegate.swift, Sources/Mixpanel.swift, Sources/MixpanelPersistence.swift
previously we were putting $distinct_id on all records, $distinct_id is disallowed on groups records, so this was causing them to be rejected by the api
=> only put $distinct_id on People records

Sources/MixpanelInstance.swift
This should hopefully fix: https://github.com/mixpanel/mixpanel-react-native/issues/132
=> pass completion handler to flush on background

Sources/MixpanelInstance.swift
pass lib name and version from super props into toggle sdk event
=> get lib name and version from super props

Sources/Track.swift
Fixes: https://github.com/mixpanel/mixpanel-swift/issues/550
=> Send time as Decimal to avoid 32-bit max int

Sources/MPDB.swift
Fix for https://github.com/mixpanel/mixpanel-swift/issues/556
=> strip whitespace in MPDB token

Sources/MPDB.swift
Hey! Here's a fix for some typos I noticed in the logs.
=> Fix typos in log

.github/workflows/iOS.yml, README.md
Pod linting fails for watchOS in Xcode 14: https://github.com/CocoaPods/CocoaPods/issues/11558
=> Disable watchOS builds in CI

Sources/MPDB.swift
A couple of SQLite optimizations 
Create indexes on order by column as [suggested by Apple](https://developer.apple.com/documentation/xcode/reducing-disk-writes#Use-appropriate-indices) and https://github.com/mixpanel/mixpanel-swift/issues/585
Enable WAL journal mode as [suggested by Apple](https://developer.apple.com/documentation/xcode/reducing-disk-writes#Use-write-ahead-logging-journaling-mode) and https://github.com/mixpanel/mixpanel-swift/issues/584
=> create indexes and enable WAL journal_mode

MixpanelDemo/MixpanelDemo/GDPRViewController.swift, MixpanelDemo/MixpanelDemo/GroupsViewController.swift, MixpanelDemo/MixpanelDemo/PeopleViewController.swift, MixpanelDemo/MixpanelDemo/TrackingViewController.swift, Sources/Network.swift, Sources/People.swift, Sources/SessionMetadata.swift
Fix for: https://github.com/mixpanel/mixpanel-swift/issues/595
=> Fix Xcode 14.3 heterogeneous collection warnings

Sources/MixpanelInstance.swift
Fixes thread safety in currentSuperProperties, unregisterSuperProperty and updateSuperProperty.
Addresses https://github.com/mixpanel/mixpanel-swift/issues/622
=> Prevent crashes in unregisterSuperProperty

Mixpanel-swift.podspec
Porting this from the Objective-C SDK: https://github.com/mixpanel/mixpanel-iphone/pull/1025
=> Use s.resources_bundle in podspec instead of s.resources

Sources/Mixpanel.swift
Address https://github.com/mixpanel/mixpanel-swift/issues/667
=> Add safeMainInstance() -> MixpanelInstance?
