Mixpanel/Decide.swift, Mixpanel/DecideRequest.swift, Mixpanel/Flush.swift, Mixpanel/FlushRequest.swift, Mixpanel/Mixpanel.swift, Mixpanel/MixpanelInstance.swift, Mixpanel/Network.swift
As master stands right now, all `MixpanelInstance` objects will use the last `serverURL` that was set on any of them.
This PR initializes `MixpanelInstance` objects with a `name` property.
* `MixpanelManager` will initialize them with the `instanceName` argument.
* The `MixpanelInstance` initializer has a default value for `name` of `UUID.uuidString()` so as not to break existing code that may bypass `MixpanelManager`.
=> Support having a different server url for each MixpanelInstance

Mixpanel/MixpanelInstance.swift, Mixpanel/Persistence.swift
Added safety check so that identify only changes the distinct_id if the given distinct_id is different from both the existing distinct_id and the alias. Required the creation of an alias property.
For reference: https://github.com/mixpanel/mixpanel-js/blob/master/src/mixpanel-core.js#L1339-L1343
=> Ported identify safety check from js lib

Mixpanel/MixpanelInstance.swift
The gesture recognizer code was missing a `?.` for non-simulator builds (Archive)
=> Add optional question mark

README.md
If you want Mixpanel in both your app *and* your app-extension, you need both pods specified in the correct targets in your `Podfile`.
=> Clear up `pod` usage

Mixpanel/MixpanelInstance.swift
Without this change, if you remove `-D DECIDE` from `OTHER_SWIFT_FLAGS` in the build settings, then compilation fails. I hope this is helpful!
=> Fix compile errors when DECIDE is not unset

Mixpanel/MixpanelInstance.swift
`mpPayload["m"]` and `mpPayload["c"]` are ints. To avoid indavertently evaluating `c` and `m` to `nil` we cast to Int instead. This is consistent with our [Obj-C SDK](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L412-L414).
=> Cast campaign_id and message_id to ints

Mixpanel/MixpanelInstance.swift, MixpanelDemo/MixpanelDemoTests/MixpanelDemoTests.swift
Updating unit tests to reflect ints in remote notification payload for campaign_id and message_id keys.
cc: @yarneo
=> Update unit tests for push notification open tracking

Mixpanel/MixpanelInstance.swift, Mixpanel/MixpanelType.swift, MixpanelDemo/MixpanelDemoTests/MixpanelDemoTests.swift
```
{
‘mp’: {
‘c’: $campaign_id,
‘m’: $message_id,
}
}
```
```
{
event: $campaign_received,
properties: {
‘campaign_id': $campaign_id,
‘message_id’: $message_id
}
}
```
```
{
‘mp’: {
‘c’: $campaign_id,
‘m’: $message_id,
‘additional_params_1’: $param1,
‘additional_params_2’: $param2,
}
}
```
```
{
event: $campaign_received,
properties: {
‘campaign_id': $campaign_id,
‘message_id’: $message_id,
‘additional_params_1’: $param1,
‘additional_params_2’: $param2,
}
}
```
=> Allow tracking journey_id in push open 

Mixpanel/MixpanelInstance.swift
Same change that was made in mixpanel-iphone lib here: https://github.com/mixpanel/mixpanel-iphone/pull/693
=> Don't require identify to merge $experiments People prop

Mixpanel/TweakPersistency.swift
Use the @objc(name) attribute to change the name of the private nested Data class as it’s exposed to Objective-C code.
=> Fix build error in swift4wip branch (Xcode 9 beta 3)

Mixpanel/UIViewSelectors.swift, Mixpanel/Variant.swift
this fixes the crash we have been seeing with the UITabSwappableImageView.
this also fixes the modification of existing a/b tests.
=> swift fixes

Mixpanel/MixpanelInstance.swift
if alias and distinctID are the same don't update the distinctID for people
=> fix identify to be consistent with obj-c

Mixpanel/MixpanelInstance.swift
improve alias invoking to not have to call identify with the original id right after
=> improve alias invoking to not have to call identify after

Mixpanel/AutomaticProperties.swift, Mixpanel/DecideRequest.swift, Mixpanel/MixpanelInstance.swift, Mixpanel/People.swift, Mixpanel/Track.swift, MixpanelDemo/MixpanelDemo/AppDelegate.swift
ensure getCurrentRadio is non-nil even though it should have been before
lock `AutomaticProperties.properties` since it's shared across mixpanel instances
=> fix setCurrentRadio crash

Mixpanel/BaseNotificationViewController.swift
Which was resolving to the main target bundle when using `type(of: self)`.
Fixes #176
=> Fix Bundle initialization

Mixpanel/TakeoverNotificationViewController~ipad.xib, Mixpanel/TakeoverNotificationViewController~iphonelandscape.xib, Mixpanel/TakeoverNotificationViewController~iphoneportrait.xib
This PR is to address the issue 
https://github.com/mixpanel/mixpanel-iphone/issues/774
"Button to dismiss fullscreen in-app message is too tiny, hard to tap"
=> Enlarge the dismiss button for in-app notfication

Mixpanel/AutomaticEvents.swift, Mixpanel/Mixpanel.swift, Mixpanel/MixpanelInstance.swift
This is to give our users the flexibility to turn automatic push tracking on and off based on needs.
=> Add automaticPushTracking parameter to be parity with ObjC version

Mixpanel/Flush.swift
The check for removing events from the queue after a successful flushRequest is removing all events from the shadowQueue. When queue.count is greater than APIConstants.batchSize, it will cause the first batch of events up to the batchSize to be sent and the remaining events in the queue to be dropped.
=> Flush all queued events in batches (#1)

Mixpanel/AutomaticEvents.swift
the `typealias` in the swizzling block was missing `@escaping`
=> fix notification tracking crash related to @noescape

Mixpanel/AutomaticEvents.swift
Add @escaping attribute on closure type argument of typealiased MyCFunction
=> Fix crash on tapping notification when built by Xcode 10

Mixpanel.xcodeproj/project.pbxproj
Building apps for simulator results in this error right now. Removing the VALID_ARCH build setting allows the builds to succeed again.
```
Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'Mixpanel')
```
=> Unset VALID_ARCH setting

.travis.yml, Mixpanel/MixpanelInstance.swift, Mixpanel/UIControlBinding.swift
- Enable an Active Compilation Condition `NO_AB_TESTING_EDITOR` to disable AB_TESTING web editor support, to disable gesture recognizer explicitly. Otherwise, it is enabled by default.
- Fix codeless tracking not able to track UITextField due to iOS 12
=> Fix UITextField codeless

Mixpanel/MixpanelInstance.swift
Reduce the chance the archived events are not in sync with the latest event queue in memory, this potentially could happen when the app goes into background or being forced quit by user.
=> Fix the issue where events could potentially be sent more than once.

Mixpanel/Persistence.swift
This uses the Obj-C ExceptionWrapper to catch the exception when trying to use NSKeyedArchiver. This also logs what happened so we can see what the issue is.
=> Issue 272: Handle archiveToFile exception and log the issue

Mixpanel/SSLSecurity.swift, Mixpanel/TweakCollection.swift, Mixpanel/TweakStore.swift
✋ Just a small fix that can improve `.reduce` performance
In previous implementation it would copy array on every iteration
In new one only one instance is created and `.append` is just linear operation
So it should go from `O(n^2)` -> `O(n)`
=> Optimize `.reduce` usage on Array

Mixpanel/AutomaticEvents.swift, Mixpanel/MixpanelInstance.swift, MixpanelDemo/MixpanelDemoTests/MixpanelAutomaticEventsTests.swift
This is to fix issues below:
Automatic Events disparity between Obj-C and Swift 
https://github.com/mixpanel/mixpanel-swift/issues/222 
(Store total app sessions, total app session length and first app open date as user properties, parity with ObjC)
Super properties are not sent with the common "First App Open" event 
https://github.com/mixpanel/mixpanel-swift/issues/189
=> add automatic events parity between Obj-C and Swift

Mixpanel.xcodeproj/project.pbxproj, Mixpanel/Decide.swift, Mixpanel/DisplayTrigger.swift, Mixpanel/InAppNotification.swift, Mixpanel/InAppNotifications.swift, Mixpanel/MixpanelInstance.swift, Mixpanel/SelectorEvaluator.swift, MixpanelDemo/MixpanelDemo.xcodeproj/project.pbxproj, MixpanelDemo/MixpanelDemoTests/InAppNotificationTest.swift, MixpanelDemo/MixpanelDemoTests/MixpanelNotificationTests.swift, MixpanelDemo/MixpanelDemoTests/SelectorEvaluaterTests.swift
**Event Triggered InApps**
Currently users have no control over when an InApp notification shows up. With this release users can now control when an InApp gets displayed based on an event that they track within their app. This "trigger" event is defined during message creation. You can additionally filter the event based on properties that are tracked along with the event for even finer controls.
=> Add support for display triggers in inapp notifications

Mixpanel/MixpanelInstance.swift, Mixpanel/Persistence.swift, MixpanelDemo/MixpanelDemoTests/MixpanelOptOutTests.swift
Change the default behavior for setting `optOutTrackingByDefault` in  the Mixpanel initialization method.
- We will not override opt out persistence with `optOutTrackingByDefault` the flag since opt-out default state is supposed to be used as an initial state while GDPR information is being collected
=> Opt-out default state won't override user opt out local persistence

Mixpanel/JSONHandler.swift
#97 is a legitimate issue. This is a proper fix.
=> Missing case in makeObjectSerializable() : NaN or infinity cannot be serialized as JSON.

Mixpanel/AutomaticEvents.swift
When swizzling ensure the category method are prefix with your framework since it has global scope
We are experiencing an issue where 2 SDK have exactly the same method signature causing a crash. Prefixing the swizzled methods with `mp_` resolves the issue something that is adviced to do when swizzling https://nshipster.com/method-swizzling/
=> Prefix swizzled method name

Mixpanel/Network.swift
prevents a crash when error & response are both null
=> Force Unwrap fix, use shared session

Mixpanel/Decide.swift, Mixpanel/Flush.swift, Mixpanel/MixpanelInstance.swift, Mixpanel/Track.swift, MixpanelDemo/MixpanelDemoTests/MixpanelAutomaticEventsTests.swift, MixpanelDemo/MixpanelDemoTests/MixpanelDemoTests.swift, MixpanelDemo/MixpanelDemoTests/MixpanelNotificationTests.swift, MixpanelDemo/MixpanelDemoTests/MixpanelOptOutTests.swift
Fixes for the following issues:
- Crash with Set.contains(_:) 
https://github.com/mixpanel/mixpanel-swift/issues/321
- MixpanelInstance.checkDecide crash
https://github.com/mixpanel/mixpanel-swift/issues/312
- (2.6.3) Crash in Persistence
https://github.com/mixpanel/mixpanel-swift/issues/310
- (2.6.3) Bad Access in Global Lock
https://github.com/mixpanel/mixpanel-swift/issues/309
=> Fix race conditions crashes

Mixpanel/InAppNotifications.swift, Mixpanel/MixpanelInstance.swift
This PR fixes a bug that has the potential for users to see duplicate InApp messages. 
When we check `decide`, we append `InAppNotification`s to `inAppNotifications` and then filter out `shownNotifications` to determine what notifications are eligible to be displayed. There were two problems that allowed for duplicates to be shown:
1.  we not removing notifications from `inAppNotifications` list when they were shown.
2. we would clear `shownNotifications` when calling `reset()`.  
This meant that when a user logs in -> sees a notification -> logs out -> logs in, `inAppNotifications` will still contain notifications that were previously seen. Since `shownNotifications` was cleared by `reset()`, we don't filter them out and they become eligible again.
With this PR, we correctly remove shown …
=> Prevent users from seeing duplicate inapps when logging out and back in

Mixpanel/MixpanelInstance.swift, Mixpanel/MixpanelType.swift, MixpanelDemo/MixpanelDemoTests/MixpanelDemoTests.swift
If you want to use Bool type for property value, please use NSNumber with Bool instead. This can avoid swift Bool type being decoded to Int from disk.
https://github.com/mixpanel/mixpanel-swift/issues/342
=> add NSNumber support as a property value type

Mixpanel/MixpanelInstance.swift, MixpanelDemo/MixpanelDemo/Info.plist, MixpanelDemo/MixpanelDemoTests/MixpanelAutomaticEventsTests.swift
Add a new public property `trackAutomaticEventsEnabled` to Mixpanel instance for toggling automatic events tracking without setting it from Mixpanel server(AutoTrack).
=> add a new public property `trackAutomaticEventsEnabled` to Mixpanel

Mixpanel/Flush.swift, Mixpanel/JSONHandler.swift, Mixpanel/MixpanelInstance.swift, Mixpanel/Persistence.swift
This PR fix potential issues with large event queues due to the unstable network and too many events being tracked within short period of time.
- make archive/unarchive always respect queue size limit (since we merge the flush queue and the tracking queue together, without this change, there is a possibility to go over the limit)
- save progress during flushing a queue,  call archive right after each batch of events being flushed successfully, this is to prevent sending duplicated events or losing events when app being terminated during the flush before it has a chance to archive the whole thing. 
- make archive always to be called inside a network queue, this is to prevent race conditions for both the flush queue and the track queue. The flush queue and track queue transitions happens in …
=> critical fix for issues with flush and archive

Mixpanel/MixpanelInstance.swift
1) Use for-where pattern instead of for -> nested if statement to be more swifty
2) Remove need to cast to NSString
3) Breakdown value strings by components, vs unsafe .substring
4) Verify component count, else break this iteration and continue the loop
=> Additional safety when reading device radio props

.travis.yml, Mixpanel/MixpanelInstance.swift
We currently listen to the radio changes during an app session for customers, i.e. LTE, GPRS, Edge, etc.(https://developer.apple.com/documentation/coretelephony/cttelephonynetworkinfo/radio_access_technology_constants)
We record this to `$radio`, a default event property collected by Mixpanel. However this will lead to noticeable  crashes since iOS 13. https://github.com/mixpanel/mixpanel-swift/issues/367
This might seem to be an issue from Apple and there is an existing open radar: https://openradar.appspot.com/46873673.  Given the relative high occurrences of crashes, we now temporarily remove the radio listener, this will only impact the scenario where the radio actually changes during an app session. `$radio` is still going to be recorded at the start of each app session and the value …
=> Temporarily remove the radio listener

Mixpanel/AutomaticEvents.swift, Mixpanel/AutomaticProperties.swift, Mixpanel/Flush.swift, Mixpanel/MixpanelInstance.swift, Mixpanel/Swizzle.swift, Mixpanel/WebSocketWrapper.swift, MixpanelDemo/MixpanelDemoTests/MixpanelBaseTests.swift
This is to address issue https://github.com/mixpanel/mixpanel-swift/issues/391
=> convert objc_sync_enter lock to GCD

Mixpanel.xcodeproj/project.pbxproj, MixpanelDemo/MixpanelDemo.xcodeproj/project.pbxproj
In order to do an Archive build of an app, using Xcode 12, the minimum deployment target must at least be iOS 9.
=> change deployment target to iOS 9 to support Xcode 12

Mixpanel/AutomaticEvents.swift, Mixpanel/Flush.swift, Mixpanel/Mixpanel.swift, Mixpanel/MixpanelInstance.swift, Mixpanel/ObjectIdentityProvider.swift, Mixpanel/ReadWriteLock.swift, Mixpanel/TweakPersistency.swift, Mixpanel/WebSocketWrapper.swift, MixpanelDemo/MixpanelDemoTests/MixpanelDemoTests.swift
- make the Mixpanel instance thread safe https://github.com/mixpanel/mixpanel-swift/issues/394
- add QoS as .utility to DispatchQueue for more energy efficiency https://github.com/mixpanel/mixpanel-swift/issues/395
=> Concurrent improvement

Mixpanel/MixpanelInstance.swift, MixpanelDemo/MixpanelDemoTests/MixpanelDemoTests.swift
- After iOS 14, accessing IFA will require an app developer to obtain an end-user's consent via an opt-in. An app will need to obtain permission to access this unique identifier, it imposes some challenges for us like caching, permissions and usage of new frameworks and doesn't add a lot of value.  We will default to random UUID instead. If you want to use a unique persistent UUID(IFV), you can define the MIXPANEL_UNIQUE_DISTINCT_ID in your  <code>Active Compilation Conditions</code> build settings. 
- Customers can still set/identify the distinct_id as IFA or `$ios_ifa property` by themselves if they have access to the advertising identifier.
=> Remove using IFA as distinct id

Sources/MixpanelInstance.swift, Sources/Network.swift
Removing a check for the alias within the identify function as it can prevent the ID from changing if alias has been called already.
=> Remove alias check

Sources/ConnectIntegrations.swift
Fix crash when integrating with urbanairship 14.0+ due to `UAirship push channelID` has been removed and changed to `UAirship channel identifier`. The fix was to `UAirship.push().channelID -> UAirship.channel().identifier)`
For more details:
https://github.com/urbanairship/ios-library/blob/main/Documentation/Migration/migration-guide-13-14.md
=> migrate to Airship 14.0 for the Urban Airship integration

Sources/WebSocket.swift
Fixes this warning:
> Using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead
=> Fix Xcode 12.5 warnings

Sources/MixpanelInstance.swift
Hello.
Thank you for mixpanel-swift.
In this pull request I did some refactoring.
=> defaultDistinctId refactoring

.github/workflows/iOS.yml, .github/workflows/macOS.yml, .github/workflows/swift.yml, MixpanelDemo/MixpanelDemo.xcodeproj/project.pbxproj, MixpanelDemo/MixpanelDemo.xcodeproj/xcshareddata/xcschemes/MixpanelDemoMac.xcscheme, MixpanelDemo/MixpanelDemo.xcodeproj/xcshareddata/xcschemes/MixpanelDemoWatch (Notification).xcscheme, MixpanelDemo/MixpanelDemoMac/AppDelegate.swift, MixpanelDemo/MixpanelDemoMac/Assets.xcassets/AccentColor.colorset/Contents.json, MixpanelDemo/MixpanelDemoMac/Assets.xcassets/AppIcon.appiconset/Contents.json, MixpanelDemo/MixpanelDemoMac/Assets.xcassets/Contents.json, MixpanelDemo/MixpanelDemoMac/Base.lproj/Main.storyboard, MixpanelDemo/MixpanelDemoMac/Info.plist, MixpanelDemo/MixpanelDemoMac/MixpanelDemoMac.entitlements, MixpanelDemo/MixpanelDemoMac/ViewController.swift, MixpanelDemo/MixpanelDemoMacTests/Info.plist, MixpanelDemo/MixpanelDemoMacTests/MixpanelBaseTests.swift, MixpanelDemo/MixpanelDemoMacTests/MixpanelDemoMacTests-Bridging-Header.h, MixpanelDemo/MixpanelDemoMacTests/MixpanelDemoTests.swift, MixpanelDemo/MixpanelDemoMacTests/MixpanelGroupTests.swift, MixpanelDemo/MixpanelDemoMacTests/MixpanelOptOutTests.swift, MixpanelDemo/MixpanelDemoMacTests/MixpanelPeopleTests.swift, MixpanelDemo/MixpanelDemoMacTests/TestConstants.swift, MixpanelDemo/MixpanelDemoMacUITests/Info.plist, MixpanelDemo/MixpanelDemoMacUITests/MixpanelDemoMacUITests.swift, MixpanelDemo/MixpanelDemoTests/MixpanelOptOutTests.swift, MixpanelDemo/Podfile, Sources/Mixpanel.swift, Sources/MixpanelInstance.swift, Sources/Persistence.swift
- This will address issues #458 and #457. 
- Add tests for macOS
=> Fix optOutTracking in macOS

MixpanelDemo/MixpanelDemo/AppDelegate.swift, MixpanelDemo/MixpanelDemoTests/MixpanelDemoTests.swift, Sources/MixpanelInstance.swift
=> Add completion closure to async apis `reset()`, `identify()` and `createAlias()` 

Sources/Network.swift
Currently `serverURL` can only set a baseURl without path like `https://yourserver.com`, with this fix, now we can set a full path `https://yourserver.com/proxypath`
=> Allow serverURL to be set with a baseURL containing full url path

MixpanelDemo/MixpanelDemo/AppDelegate.swift, MixpanelDemo/MixpanelDemoTests/MixpanelAutomaticEventsTests.swift, MixpanelDemo/MixpanelDemoTests/MixpanelBaseTests.swift, MixpanelDemo/MixpanelDemoTests/MixpanelDemoTests.swift, MixpanelDemo/MixpanelDemoTests/MixpanelOptOutTests.swift, MixpanelDemo/MixpanelDemoTests/MixpanelPeopleTests.swift, Sources/AutomaticEvents.swift, Sources/Group.swift, Sources/Mixpanel.swift, Sources/MixpanelInstance.swift, Sources/People.swift, Sources/Track.swift
- Fix  `First App Open` not always being able to be triggered
- Add additional param `trackAutomaticEvents` in `initialize`: Whether or not to collect common mobile events
=> fix  `First App Open` not always being able to be triggered

MixpanelDemo/MixpanelDemoTests/MixpanelDemoTests.swift, Sources/Mixpanel.swift, Sources/MixpanelInstance.swift, Sources/Track.swift
Add the param `useUniqueDistinctId ` to `initialize` if you want to use IFV(identifierForVendor) as the `distinct_id` and prefer using it over 
Active Compilation Conditions `MIXPANEL_UNIQUE_DISTINCT_ID`
=> add useUniqueDistinctId parameter

MixpanelDemo/MixpanelDemoMacTests/TestConstants.swift, MixpanelDemo/MixpanelDemoTests/TestConstants.swift, Sources/FlushRequest.swift
set the content-type header to application/json to prevent certain payloads from being rejected by the server
=> set content-type to application/json

Sources/JSONHandler.swift
3595189c6fec26ee86e92e8c96aa5ec09a23595f broke the build, by redeclaring the same variable `data` in the same scope
=> fix build issue in JSONHandler

.github/workflows/iOS.yml, MixpanelDemo/MixpanelDemoTests/MixpanelAutomaticEventsTests.swift, Sources/Mixpanel.swift, Sources/MixpanelInstance.swift, Sources/MixpanelPersistence.swift
`trackAutomaticEvents` param in `initialize`  should take precedence over `Autotrack` settings from the Mixpanel, but if `trackAutomaticEvents` is not set, should respect `Autotrack` settings from the Mixpanel.
=> Fix automatic events settings

Sources/AutomaticProperties.swift
This PR adds logic to check if the app is a "Designed for iPad" app running on macOS and if so, sets the `$os` to macOS. Unfortunately, there is no API that reports the correct macOS version for "Designed for iPad" apps running on macOS, so we omit it rather than mis-report
=> check for ios app on mac in automatic props

Sources/Mixpanel.swift, Sources/MixpanelInstance.swift
This solves a data race where the server URL is mutated
while is read during the initial flush triggered when
the Mixpanel instance is created.
=> Allow setting server URL during initialization

MixpanelDemo/MixpanelDemo.xcodeproj/xcshareddata/xcschemes/MixpanelDemoWatch (Notification).xcscheme, MixpanelDemo/MixpanelDemo.xcodeproj/xcshareddata/xcschemes/MixpanelDemoWatch.xcscheme, MixpanelDemo/MixpanelDemoTests/MixpanelDemoTests.swift, Sources/MixpanelInstance.swift
When you call the API `createAlias`, there is an implicit `identify` call inside the API done for you. This will keep your signup funnels working correctly in most cases. However, if that is not what you want, this PR will allow you to not call `identify` by specifying `andIdentify` to `false`.
Please also note: With Mixpanel Identity Merge enabled, calling alias is no longer required but can be used to merge two IDs in scenarios where `identify` would fail
=> add an option for 'createAlias' for not calling identify

MixpanelDemo/MixpanelDemoTests/MixpanelBaseTests.swift, MixpanelDemo/MixpanelDemoTests/MixpanelDemoTests.swift, Sources/AutomaticEvents.swift, Sources/Mixpanel.swift, Sources/MixpanelInstance.swift, Sources/MixpanelPersistence.swift, Sources/Track.swift
This PR will add support for multiple instances under the same token. Just specify an `instanceName` in `initialize`.
```
...
/**
Initializes an instance of the API with the given project token.
Returns a new Mixpanel instance API object. This allows you to create more than one instance
of the API object, which is convenient if you'd like to send data to more than
one Mixpanel project from a single app.
...
parameter instanceName:    Optional. The name you want to uniquely identify the Mixpanel Instance.
It is useful when you want more than one Mixpanel instance under the same project token.
...
*/
@discardableResult
open class func initialize(token apiToken: String,
flushInterval: Double = 60,
instanceName: String? = nil,
optOutTrackingByDefault: Bool = false,
trackAutomaticEvents: Bool? …
```
=> add support for multiple instances under the same token

MixpanelDemo/MixpanelDemo/AppDelegate.swift, MixpanelDemo/MixpanelDemoTests/MixpanelDemoTests.swift, Sources/MPDB.swift
Fix for https://github.com/mixpanel/mixpanel-swift/issues/564
=> Only use alphanumerics in MPDB token strings

Mixpanel-swift.podspec, Mixpanel.xcodeproj/project.pbxproj
Fix for...
```
➜  mixpanel-swift git:(master) pod trunk push Mixpanel-swift.podspec --allow-warnings                                                                                                                                                 git:(master|)
Updating spec repo `trunk`
Validating podspec
-> Mixpanel-swift (4.0.4)
- NOTE  | [Mixpanel-swift/Complete,Mixpanel-swift/Core] xcodebuild:  note: Using codesigning identity override: -
- NOTE  | [Mixpanel-swift/Complete,Mixpanel-swift/Core] xcodebuild:  note: Building targets in dependency order
- NOTE  | [Mixpanel-swift/Complete,Mixpanel-swift/Core] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to …
```
=> bump podspec deployment targets

Sources/Mixpanel.swift
Don't fire this assert in the simulator (SwiftUI Preview), as the new SwiftUI lifecycle doesn't initialize Main view controller in child views so the SDK will likely not be configured
=> SwiftUI preview fix

Sources/MixpanelInstance.swift
Access the timedEvents property inside of a readWriteLock.  Fixes crashes when client tries to read and write to timedEvents property at the same time.
=> Access the timedEvents property inside of a readWriteLock.

Sources/Flush.swift
The value could have been modified between evaluating the statement and executing the block.
See https://github.com/mixpanel/mixpanel-swift/issues/582
=> Check flush interval > 0 inside the dispatch block

Sources/AutomaticEvents.swift, Sources/Flush.swift, Sources/Mixpanel.swift, Sources/MixpanelInstance.swift, Sources/ReadWriteLock.swift
I was seeing large memory growth when offline with _lots_ of items waiting to be flushed to the mp service. i had ~5000 events queued while offline, and the work done on these dispatch queues wasn't getting cleaned up, causing an explosion in otherwise collectable memory.
my understanding is that `DispatchQueue()` will default to `autoreleaseFrequency=.never`, which can leave those autoreleased objects hanging around in memory for undefined amounts of time.
=> Setting explicit autorelease frequency

.github/workflows/iOS.yml, README.md, Sources/MixpanelInstance.swift, Sources/ReadWriteLock.swift
This PR combines the changes from the following PRs with the necessary config changes needed to run CI tests against them...
https://github.com/mixpanel/mixpanel-swift/pull/576 - thanks @vikas171999
https://github.com/mixpanel/mixpanel-swift/pull/579 - thanks @adamwulf
https://github.com/mixpanel/mixpanel-swift/pull/583 - thanks @julsh
https://github.com/mixpanel/mixpanel-swift/pull/588 - thanks @prydain007
=> Various Community PRs

Sources/Constants.swift, Sources/Flush.swift, Sources/Group.swift, Sources/MixpanelInstance.swift, Sources/People.swift
This will greatly improve the performance and reduce crashes. Thanks @thibauddavid, #594
=> Set the number of events per flush to 1,000 to reduce memory footprint

Sources/AutomaticProperties.swift
address the crash issue from RN: https://github.com/mixpanel/mixpanel-react-native/issues/171
=> Fix potential crash automatic properties

MixpanelDemo/MixpanelDemoTests/MixpanelDemoTests.swift, Sources/Constants.swift, Sources/Flush.swift, Sources/MixpanelInstance.swift
Add the following property `flushBatchSize`:
The flushBatchSize property controls the number of events sent in a single network request to the Mixpanel server.
Batch size affects how data is flushed from the client to Mixpanel. By configuring the size of the batch, you can
optimize network usage and control how frequently the client communicates with the server.
Usage: 
`mixpanel.flushBatchSize = 20`
=> add a new property 'flushBatchSize' for fine tuning the network request

Sources/AutomaticProperties.swift, Sources/Constants.swift
Fixes so Mixpanel builds in both Xcode 15 prod and betas, making it possible to work with visionOS targets.
fixes mixpanel/mixpanel-swift#612
=> Fixes so project builds for visionOS

Sources/AutomaticEvents.swift, Sources/AutomaticProperties.swift, Sources/MixpanelInstance.swift
This adds support for sending os and os_version for visionOS along with Automatic Events.
I'm sure there is more parts of mixpanel-swift that would function on visionOS that I've missed.
=> visionOS Operating System & Version along with Automatic Events

Mixpanel.xcodeproj/project.pbxproj, MixpanelDemo/MixpanelDemo.xcodeproj/project.pbxproj, Sources/PrivacyInfo.xcprivacy
This PR adds a privacy manifest to declare the use of the required API for UserDefaults with the following reason:
```
1C8F.1
Declare this reason to access user defaults to read and write information that is only accessible to the apps, app extensions, and App Clips that are members of the same App Group as the app itself.
This reason does not permit reading information that was written by apps, app extensions, or App Clips outside the same App Group or by the system. This reason also does not permit writing information that can be accessed by apps, app extensions, or App Clips outside the same App Group.
```
Addresses: https://github.com/mixpanel/mixpanel-swift/issues/620
=> Add privacy manifest

Sources/Flush.swift, Sources/FlushRequest.swift, Sources/MixpanelInstance.swift, Sources/Network.swift
=> Fix the crash for FlushRequest.sendRequest

Sources/MixpanelInstance.swift
This PR enables cross-SDK communication for registering super properties by using Notification.
=> Enable cross SDK communication for registratering super properties.

Sources/MixpanelInstance.swift, Sources/ReadWriteLock.swift
Since the `UserDefaults` calls made by `saveIdentity` cause blocking `NSNotifications` to be emitted to the main thread, calling `saveIdentity` under the write lock can cause deadlocks.
Since the `saveIdentity` call only reads state it’s now moved to only take a read lock instead of being under the write lock.
In my Mac app I initialise Mixpanel on a background thread to avoid blocking the main thread during launch. This works fine for most users, however when the app loses focusses immediately during the very first launch Mixpanel deadlocks. Freezing the app completely. (This happens most often when users install the app through the App Store en then click the "Open" button in the App Store itself, this launches the app, but als takes back the focus immediately.)
Attached here you can …
=> Avoid deadlock during first time initialisation

Mixpanel-swift.podspec, Package.swift
The Xcode project build settings were actually already bumped to 12.0 a few weeks ago in https://github.com/mixpanel/mixpanel-swift/pull/653
This is needed now because Flutter supports iOS 12 and later and this SDK is wrapped by our Flutter SDK (see https://github.com/mixpanel/mixpanel-flutter/issues/186).
Since this is technically a breaking change for any app that still targets iOS 11, this will be released with a major version bump.
=> Bump minimum iOS to 12 in Package and Pod

.github/workflows/iOS.yml, MixpanelDemo/MixpanelDemoTests/MixpanelFeatureFlagTests.swift, Sources/FeatureFlags.swift
This is primarily so we can put feature flag evaluation behind a CDN
=> use HTTP GET for feature flags

MixpanelDemo/MixpanelDemoTests/MixpanelFeatureFlagTests.swift, Sources/FeatureFlags.swift
Plumbs ExperimentID, isExperimentActive, and isQATester, optional properties that may be present in the /flags API response, through to the tracked $experiment_started event.
This pull request enhances feature flag support by adding optional experiment-related properties to the `MixpanelFlagVariant` model and ensuring these properties are correctly decoded, tracked, and tested. The changes improve the ability to track experiment metadata with feature flag usage, increasing flexibility for experimentation and analytics.
* Added optional fields `experimentID`, `isExperimentActive`, and `isQATester` to the `MixpanelFlagVariant` struct, allowing experiment metadata to be attached to flag variants.
* Updated decoding logic in `MixpanelFlagVariant` to properly parse these optional fields from …
=> Plumb additional flags properties through to exposure event
